---
# User identity — leave empty to be prompted on first Ansible run
user_name: ""
user_email: ""

# Private machine specific packages
profile_packages:
  - vlc
  # - steam           # uncomment for gaming setup
  # - obs-studio

# Private-specific vars
# (add as needed)
