---
# asdf binary (provided by brew)
asdf_bin: "{{ brew_prefix }}/bin/asdf"

# Where to symlink nvim binary
neovim_bin_dir: "{{ lookup('env', 'HOME') }}/.local/bin"

# Brew packages this role needs
neovim_brew_packages:
  - asdf
  - rust
  - node
  - lazygit

# Brew casks this role needs
neovim_brew_casks:
  - font-ubuntu-sans-nerd-font

# Apt packages required by neovim and its plugins
neovim_apt_packages:
  - build-essential
  - luarocks
  - pkg-config
  - ripgrep
  - fd-find
  - python3-pynvim
  - xclip
